### ISSUE TITLE
version 1.0.0

### ISSUE THREAD

**Issue by missinglink** [mapbox/geojson-extent#12]
Heya,

I was looking through our dependencies today and found that this lib is being published as `v0.3.2`.
The [semantic versioning spec](https://semver.org/#spec-item-4) indicates that this version number isn't meant for production use:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

Since `geojson-extent` is mature and stable, would you consider releasing a `1.0.0`?

> Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

The reason I ask is that we were recently stung by a `0.x.x` package releasing breaking changes on the *minor* version number, which apparently is fine according to the spec, as a result we're doing an audit of all deps with a zero major number and likely avoiding them in production.

**Comment by mapsam** [comment]
Hey @missinglink 👋 I'm working on some security updates in #13 and agree we should tag v1.x since this has been out long enough. I'm going to tag an updated patch in the v0.x series with the security updates, and then will tag a v1.x release without any changes.

**Comment by mapsam** [comment]
Just a heads up @missinglink that I'll be tagging 0.4.0, which includes changes from #5 that haven't been published. This technically could be considered a breaking change if you've been using this library with invalid geojson type fields. This will also be included in v1.x.

**Comment by mapsam** [comment]
`@mapbox/geojson-extent@1.0.0` published!
