### ISSUE TITLE
Publish under @mapbox npm

### ISSUE THREAD

**Issue by stevewillard** [mapbox/geojson-extent#6]
Are there plans to publish this under the @mapbox namespace in npm? I get this message when running `yarn install`

`warning geojson-extent > extent@0.2.0: This module is now under the @mapbox namespace: install @mapbox/extent instead`

I don't really want to use `@mapbox/extent` - it seems to have a much different API than this library.

**Comment by tmcw** [comment]
That error message is trying to say that `geojson-extent`'s _dependency_, `extent`, is now namespaced, not that you need to use `@mapbox/extent`. We'll namespace this module, but it will continue to have the same api.

**Comment by stevewillard** [comment]
Ah, gotcha. Thanks :)

**Comment by tmcw** [comment]
👍 All polished up, `@mapbox/geojson-extent` is published. Thanks for flagging this issue!
