### ISSUE TITLE
What does the variable bbox do in getExtent?

### ISSUE THREAD

**Issue by Rovanion** [mapbox/geojson-extent#8]
I was reading the code of index.js as I was working to implement a function just like `getExtent` with the minor difference that would be capable of calculating the bounding box of multiple geoJSONs. But as I was working with the code I found a variable `bbox` which was declared but never used on [line 42].

Looking at the git blame and history unfortunately doesn't bring me closer to a guess as to what its for. Even in the first commit when it was introduced the variable is seemingly never used. Could you shed some light on its purpose?

[line 42]: https://github.com/mapbox/geojson-extent/blob/master/index.js#L42

**Comment by bhousel** [comment]
Hey @Rovanion - it looks like the `bbox` variable was never used.  My guess is that the original author intended to calculate the bounding box with a loop, but then changed his mind and pulled in the `extent` dependency to perform that task instead.
